/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import observador.IObservador;
import observador.Observable;
import parkingsystem.Entidad.Parking;
import parkingsystem.Fachada;
import parkingsystem.SistemaParking;

/**
 *
 * @author Embrono
 */
public class TableroDeControl extends javax.swing.JFrame implements IObservador{

    /**
     * Creates new form TableroDeControl
     */
    public TableroDeControl() {
        initComponents();
        Fachada.getInstancia().agregarObservador(this);
        DibujarGridParking();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelEstadiasValue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelFacturacionValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDashBoard = new javax.swing.JTable();
        jButtonCartelera = new javax.swing.JButton();
        jButtonPrecios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAnomalias = new javax.swing.JTable();
        jCheckBoxMonitor = new javax.swing.JCheckBox();
        jButtonCerrar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tablero de control");

        jLabel2.setText("Estadias");

        jLabelEstadiasValue.setText("0");

        jLabel3.setText("Facturacion:");

        jLabelFacturacionValue.setText("0");

        jTableDashBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Parking", "# Ocupadas", "# Libres", "Estado", "Factor Demanda", "# Estadias", "Multas", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDashBoard);
        if (jTableDashBoard.getColumnModel().getColumnCount() > 0) {
            jTableDashBoard.getColumnModel().getColumn(0).setResizable(false);
            jTableDashBoard.getColumnModel().getColumn(1).setResizable(false);
            jTableDashBoard.getColumnModel().getColumn(2).setResizable(false);
            jTableDashBoard.getColumnModel().getColumn(3).setResizable(false);
            jTableDashBoard.getColumnModel().getColumn(4).setResizable(false);
            jTableDashBoard.getColumnModel().getColumn(5).setResizable(false);
            jTableDashBoard.getColumnModel().getColumn(6).setResizable(false);
            jTableDashBoard.getColumnModel().getColumn(7).setResizable(false);
        }

        jButtonCartelera.setText("Cartelera");
        jButtonCartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCarteleraMouseClicked(evt);
            }
        });

        jButtonPrecios.setText("Precios");
        jButtonPrecios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPreciosMouseClicked(evt);
            }
        });

        jTableAnomalias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha/Hora", "Propietario", "Codigo de anomalia", "Cochera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAnomalias);
        if (jTableAnomalias.getColumnModel().getColumnCount() > 0) {
            jTableAnomalias.getColumnModel().getColumn(0).setResizable(false);
            jTableAnomalias.getColumnModel().getColumn(1).setResizable(false);
            jTableAnomalias.getColumnModel().getColumn(2).setResizable(false);
            jTableAnomalias.getColumnModel().getColumn(3).setResizable(false);
        }

        jCheckBoxMonitor.setText("Monitoriar anomalias");
        jCheckBoxMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMonitorActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPrecios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCartelera))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstadiasValue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelFacturacionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonCerrar)
                                    .addComponent(jCheckBoxMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEstadiasValue)
                    .addComponent(jLabel3)
                    .addComponent(jLabelFacturacionValue))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCartelera)
                    .addComponent(jButtonPrecios))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxMonitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCerrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMonitorActionPerformed

    private void jButtonPreciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPreciosMouseClicked
        // TODO add your handling code here:
        new ListaDePrecio(this, false).setVisible(true);
    }//GEN-LAST:event_jButtonPreciosMouseClicked

    private void jButtonCarteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCarteleraMouseClicked
        // TODO add your handling code here:
        new CarteleraElectronica(this, false).setVisible(true);
    }//GEN-LAST:event_jButtonCarteleraMouseClicked

    private void jButtonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarMouseClicked
        // TODO add your handling code here:
        Fachada.getInstancia().quitarObservador(this);
        this.dispose();
        
    }//GEN-LAST:event_jButtonCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroDeControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCartelera;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonPrecios;
    private javax.swing.JCheckBox jCheckBoxMonitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEstadiasValue;
    private javax.swing.JLabel jLabelFacturacionValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableAnomalias;
    private javax.swing.JTable jTableDashBoard;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(Object evento, Observable origen) {
    }
    
    public void DibujarGridParking(){
         ArrayList<Parking> listaParkings = Fachada.getInstancia().getParkings();
        
        // Crear el modelo de la tabla
        DefaultTableModel model = new DefaultTableModel();
        
        // Añadir columnas
        model.addColumn("Parking");
        model.addColumn("# Ocupadas");
        model.addColumn("# Libres");
        model.addColumn("Estado");
        model.addColumn("Factor Demanda");
        model.addColumn("# Estadias");
        model.addColumn("Multas");
        model.addColumn("SubTotal");
        
        // Establecer el número de filas
        model.setRowCount(listaParkings.size());
        
        int fila = 0;
        
        // Rellenar las filas con los datos de Parking
        for (Parking p : listaParkings) {
            //model.setValueAt(p.getNombre(), fila, 0);
            //model.setValueAt(p.getNumeroOcupadas(), fila, 1);
            //model.setValueAt(p.getNumeroLibres(), fila, 2);
            //model.setValueAt(p.getEstado(), fila, 3);
            //model.setValueAt(p.getFactorDemanda(), fila, 4);
            //model.setValueAt(p.getNumeroEstadias(), fila, 5);
            //model.setValueAt(p.getNumeroMultas(), fila, 6);
            //model.setValueAt(p.getSubTotal(), fila, 7);
            
            model.setValueAt("Test 1: "+ fila, fila, 0);
            model.setValueAt("Test 1: "+ fila, fila, 1);
            model.setValueAt("Test 1: "+ fila, fila, 2);
            model.setValueAt("Test 1: "+ fila, fila, 3);
            model.setValueAt("Test 1: "+ fila, fila, 4);
            model.setValueAt("Test 1: "+ fila, fila, 5);
            model.setValueAt("Test 1: "+ fila, fila, 6);
            model.setValueAt("Test 1: "+ fila, fila, 7);
            fila++;
        }
        
        // Establecer el modelo en la tabla
        jTableDashBoard.setModel(model);
    }
}
